spring:
  datasource:
    # MySQL
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true # 连接地址
    username: root # 用户名
    password: 123 # 密码
  data:
    # Redis
    redis:
      host: 127.0.0.1 # 地址
      port: 6379 # 端口
      password: 123 # 密码
      database: 0 # 指定数据库序号
